name: GitHub Actions Demo
run-name: this is a test demo
on: [push]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: "查看当前路径和文件"
        run: |
          pwd 
          ls

      - name: "编译代码"
        run: |
          mkdir output
          gcc test.c -o output/test

      - name: "运行代码"
        run: ./output/test
