name: GitHub Actions Demo
run-name: this is a test demo
on: [push]

permissions:
  contents: write

jobs:
  test_job:
    runs-on: ubuntu-22.04
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: "查看当前路径和文件"
        run: |
          pwd 
          ls

      - name: "编译代码"
        run: |
          mkdir output
          gcc test.c -o output/test

      - name: "编译armbian"
        run: |
          # git clone --depth=1 --branch=main https://github.com/armbian/build
          # cd build
          # ./compile.sh build BOARD=pine64 BRANCH=current BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no RELEASE=bookworm
          # cd ..
          chmod +x build.sh
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C
          # ./build.sh --board znp_k1/
          git lfs install
          git lfs track "*.img"
          git add .gitattributes
          cp ./output/test ./output/test.img
          dd if=/dev/zero of=./output/test.img count=200 bs=1M
          
      - name: "运行代码"
        run: ./output/test

      - name: "部署"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: output/
          
