name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: "test_pwd_ls" 
        run: |
          pwd
          ls
