name: GitHub Actions Demo
run-name: this is a test demo
on:
  push

permissions:
  contents: write

jobs:
  test_job:
    runs-on: ubuntu-22.04
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: "编译armbian"
        run: |
          chmod +x build.sh
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C
          ./build.sh --board znp_k1/
          sudo apt install gzip
          tar -cvf - build/output/images/ | gzip > output/znp_k1.gz

      - name: "发布"
        uses: ncipollo/release-action@v1
        with:
          # 如果版本已经存在，是否应该更新它
          allowUpdates: true
          # 版本的可选名称。 如果省略，将使用标签
          name: "test"
          tag: "main"
          # 要包含到Release Assets中的文件
          artifacts: "./output/znp_k1.gz"
          # 会使用一个临时的token来创建Release
          token: ${{ github.token }}
          # 自动生成一些变化列表之类的内容。
          generateReleaseNotes: true
          
